#!/bin/bash

# 1. VARIABLES (Storing a single piece of data)
GREETING="Hello"
echo "$GREETING! Let's learn Shell Scripting."
echo "-----------------------------------"


# 2. ARRAYS (Storing a list of data)
COURSES=("Linux" "Git" "Docker" "AWS")

# Indexing starts at 0. So [0] is Linux.
echo "First course in the list: ${COURSES[0]}"

# [@Reference] prints all items in the array.
echo "All courses available: ${COURSES[@]}"
echo "-----------------------------------"


# 3. FUNCTIONS (Reusable blocks of code)
# This function checks a score and decides if it's a pass or fail.
check_status() {
    # '$1' represents the first argument passed into the function.
    
    # 4. CONDITIONS (If / Else logic)
    # '-ge' stands for 'Greater than or Equal to'
    if [ $1 -ge 35 ]; then
        echo "Result: You passed the exam! (Score: $1)"
    else
        echo "Result: You failed the exam. (Score: $1)"
    fi
}


# Let's call/use the function with different scores:
check_status 40
check_status 20
echo "-----------------------------------"


# 5. LOOPS (Doing a repetitive task automatically)
echo "Printing our course list using a 'for' loop:"

for COURSE in "${COURSES[@]}"
do
    echo "-> Currently learning: $COURSE"
done
echo "-----------------------------------"