#!/bin/bash
ID=$(id -u)
echo "1.ID value is: ${ID}"
echo '2.ID value not print if single quote given: ${ID}'
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

TIMESTAMP=$(date +%F-%H-%M-%S)
LOGFILE="/tmp/$0-$TIMESTAMP.log"

if [ $ID -ne 0 ]
then
    echo -e "$R ERROR:: Please run this script with root access $N"
    exit 1 # you can give other than 0
else
    echo "3.You are root user" 
    echo -e "4.You are $G root user"
    #-e colors in the echo command.
    echo -e "5.$G You are root user $N" 
    #$N: Resets the terminal color back to normal so subsequent text doesn't stay green.
    echo -e "6.$G You are root user"
fi 




