#!/bin/bash
ID=$(id -u)
TIMESTAMP=$(date +%F-%H-%M-%S)
LOGFILE="/tmp/$0-$TIMESTAMP.log"

echo "script started executing at $TIMESTAMP" &>> $LOGFILE

if [ $ID -ne 0 ]
then
    echo "ERROR:: Please run this script with root access"
    exit 1 # you can give other than 0
else
    echo "You are root user"
fi 

yum install mysql -y
# $? -special variable -stores exit status (0=successful,non-zero/1-255=Failed)
if [ $? -ne 0 ]
then
    echo "ERROR:: Installing MySQL is failed"
    exit 1
else
    echo "Installing MySQL is SUCCESS"
fi
#&>> special operator used to send/redirect both standard output(regular messages) 
# and standard error (error messages) of a command and append them to the end of a file.
yum install mysql -y &>> $LOGFILE

VALIDATE $? "Validation_In the server,MySQL Installation is"
VALIDATE(){
    if [ $1 -ne 0 ]
    then
        echo -e "$2 *** $R FAILED $N"
    else
        echo -e "$2 *** $G SUCCESS $N"
    fi
}